import { FilterOption } from '@/components/FilterDropdown'

export const LOCATION_OPTIONS: FilterOption[] = [
  { value: '', label: 'Any country' },
  { value: 'Remote', label: 'Remote' },
  { value: 'Australia', label: 'Australia' },
  { value: 'Austria', label: 'Austria' },
  { value: 'Belgium', label: 'Belgium' },
  { value: 'Brazil', label: 'Brazil' },
  { value: 'Canada', label: 'Canada' },
  { value: 'Czech Republic', label: 'Czech Republic' },
  { value: 'Denmark', label: 'Denmark' },
  { value: 'Finland', label: 'Finland' },
  { value: 'France', label: 'France' },
  { value: 'Germany', label: 'Germany' },
  { value: 'India', label: 'India' },
  { value: 'Ireland', label: 'Ireland' },
  { value: 'Italy', label: 'Italy' },
  { value: 'Japan', label: 'Japan' },
  { value: 'Mexico', label: 'Mexico' },
  { value: 'Netherlands', label: 'Netherlands' },
  { value: 'New Zealand', label: 'New Zealand' },
  { value: 'Norway', label: 'Norway' },
  { value: 'Poland', label: 'Poland' },
  { value: 'Portugal', label: 'Portugal' },
  { value: 'Singapore', label: 'Singapore' },
  { value: 'South Korea', label: 'South Korea' },
  { value: 'Spain', label: 'Spain' },
  { value: 'Sweden', label: 'Sweden' },
  { value: 'Switzerland', label: 'Switzerland' },
  { value: 'UK', label: 'UK' },
  { value: 'UK:Oxfordshire', label: 'Oxfordshire', indent: true },
  { value: 'UK:London', label: 'London', indent: true },
  { value: 'UK:Scotland', label: 'Scotland', indent: true },
  { value: 'UK:West of England', label: 'West of England', indent: true },
  { value: 'UK:Leicester', label: 'Leicester', indent: true },
  { value: 'UK:Manchester', label: 'Manchester', indent: true },
  { value: 'US', label: 'US' },
  { value: 'Other', label: 'Other' },
]
